// <auto-generated />
using EyeTvoice_project.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EyeTvoice_project.Migrations
{
    [DbContext(typeof(LessonDbContext))]
    [Migration("20240417133752_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EyeTvoice_project.Entity.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LessonEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TitleName = "1-lesson"
                        },
                        new
                        {
                            Id = 2,
                            TitleName = "2-lesson"
                        },
                        new
                        {
                            Id = 3,
                            TitleName = "3-lesson"
                        },
                        new
                        {
                            Id = 4,
                            TitleName = "4-lesson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
